### ISSUE TITLE
When executing on Windows creating the gitignore file results in a FileExistsError: [WinError 183]

### ISSUE THREAD

**Issue by tuvokki** [OptimalBPM/angular-schema-form-plugins#8]
The following happens when executing on windows:

```
  > "c:\Programs\Python35\python.exe" create_new_add_on.py --name="testi" --author="Author Name"
  Traceback (most recent call last):
    File "create_new_add_on.py", line 59, in <module>
      mass_replace(_destination, "Minimal", _add_on_name.capitalize())
    File "c:\Research\SchemaForms\tools\lib\mass_replace.py", line 40, in mass_replace
      file_replace(fullname, pat, s_after)
    File "c:\Research\SchemaForms\tools\lib\mass_replace.py", line 31, in file_replace
      os.rename(out_fname, fname)
  FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'c:\\Research\\SchemaForms\\tools\\testi\\.gitignore.tmp' -> 'c:\\Research\\SchemaForms\\tools\\testi\\.gitignore'
```

Please use shutil in mass replace to prevent FileExistsError: [WinError 183]

**Comment by nicklasb** [comment]
Good catch! I don't test it under windows, do you have any possibility to create a PR for that?

**Comment by nicklasb** [comment]
Oh, i just saw the PR, thanks for your help!

**Comment by tuvokki** [comment]
Glad to be of assistance!
